"""empty message

Revision ID: 83229fe333bf
Revises: 7a0c8ad8229a
Create Date: 2020-08-17 15:12:20.349310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83229fe333bf'
down_revision = '7a0c8ad8229a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    # ### end Alembic commands ###
