"""empty message

Revision ID: 966531827e4d
Revises: 83229fe333bf
Create Date: 2020-08-17 15:44:01.539418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966531827e4d'
down_revision = '83229fe333bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'date_created')
    # ### end Alembic commands ###
